# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a76400d6f8156b7c9fb1ec6cb49065057fb73a4a78a213ff11e83841278111ac1945c54a432d0c963e701d59c61c80ac3b89f1e94e393feb86998f63aaec651

test:
  secret_key_base: 78e5cec9405309db16ed0f06bd7fd0745e31c729d2db8aab23b33867a63e64a4f23499d88dcea7e7e6b74007d5b28406717a28a4be870aab01604214cb19ded1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
